version: '3.8'

services:
  local_batch:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: 'local_batch'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./project/src:/service/src
      - ./project/tests:/service/tests
    ports:
      - 8000:8000
    env_file:
      - ./env/common.env
      - ./env/local.env
    networks:
      - default
      - shared-network
    command: >
      bash -c '
        while :; do sleep 10; done
      '
networks:
  shared-network:
    external: true
