version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter_lab/Dockerfile
    container_name: 'jupyter'
    working_dir: '/notebook'
    tty: true
    volumes:
      - ./notebook:/notebook
    ports:
      - 8888:8888
    networks:
      - default
      - shared-network
    env_file:
      - ./env/common.env
      - ./env/secrets.env
    command: start-notebook.sh --NotebookApp.token=''

networks:
  shared-network:
