version: '3.8'
services:
  local_api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
      args:
        BUILD_MODE: api
    container_name: 'local_api'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./project/src:/service/src
    ports:
      - 8000:8000
    networks:
      - default
      - shared-network
    env_file:
      - ./env/common.env
      - ./env/local.env
    command: >
      bash -c '
        python src/api.py
      '
networks:
  shared-network:
    external: true
