version: '3.8'
services:
  gcp_api_be:
    build:
      context: ./docker/gcp/
      args:
        BUILD_MODE: api
    container_name: 'gcp_api_be'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./src:/service/src
    ports:
      - 8010:8080
    networks:
      - default
      - shared-network
    env_file:
      - ./env/common.env
      - ./env/gcp.env
    command: >
      sh -c '
        pip install -r src/requirements.txt -t ./site-packages/
        pip install -r src/requirements.txt
        functions-framework --target gcp_app --source gcp_api.py --debug
      '
  aws_api_be:
    build:
      context: ./docker/aws/
      args:
        BUILD_MODE: api
    container_name: 'aws_api_be'
    working_dir: '/var/task'
    tty: true
    ports:
      - 8020:8080
    volumes:
      - ./src:/var/task/src
      - ~/.aws:/root/.aws
    networks:
      - default
      - shared-network
    env_file:
      - ./env/common.env
      - ./env/aws.env
    entrypoint: >
      bash -c '
      pip install -r src/requirements.txt &&
      /lambda-entrypoint.sh aws_api.handler
      '
  local_api_be:
    build:
      context: ./docker/local/
      args:
        BUILD_MODE: api
    container_name: 'local_api_be'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./src:/service
    ports:
      - 8000:8000
    networks:
      - default
      - shared-network
    env_file:
      - ./env/common.env
      - ./env/local.env
    command: >
      bash -c '
        pip install -r requirements.txt
        python api.py
      '
networks:
  shared-network:
    external: true
