version: "3.8"
services:
  local:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: "local"
    working_dir: "/service/src"
    tty: true
    volumes:
      - ./project/src:/service/src
    ports:
      - 8000:8000
    networks:
      - default
      - python-app-network
    env_file:
      - ./env/common.env
      - ./env/local_app.env
      - ./env/secrets.env
    command: >
      bash -c '
        uvicorn api:app --reload --host 0.0.0.0 --port 8000
      '

networks:
  python-app-network:
